version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/boos-miniature-feed/api/v2/package
  api_key:
    secure: 8MecWJQT2OS9MTDI+tL14eybHJ7BZnudAP8z7SV+P0eCeGwoTwPUnD64w7qOoQy6
  skip_symbols: true
  on:
    branch: master

